// generated by model/fixed_golden.py - do not edit
// halfband stage coefficients g[i] = 2*h[2i], Q.24, i < m
function signed [24:0] hb_coef;
  input integer stage;
  input integer i;
  begin
    hb_coef = 25'sd0;
    case (stage)
      1: case (i)
        0: hb_coef = -25'sd1;
        1: hb_coef = 25'sd473;
        2: hb_coef = -25'sd8015;
        3: hb_coef = 25'sd58716;
        4: hb_coef = -25'sd267729;
        5: hb_coef = 25'sd901938;
        6: hb_coef = -25'sd2624855;
        7: hb_coef = 25'sd10328082;
        default: hb_coef = 25'sd0;
      endcase
      2: case (i)
        0: hb_coef = 25'sd1;
        1: hb_coef = -25'sd918;
        2: hb_coef = 25'sd18219;
        3: hb_coef = -25'sd143000;
        4: hb_coef = 25'sd670146;
        5: hb_coef = -25'sd2369501;
        6: hb_coef = 25'sd10213660;
        default: hb_coef = 25'sd0;
      endcase
      3: case (i)
        0: hb_coef = 25'sd1;
        1: hb_coef = -25'sd918;
        2: hb_coef = 25'sd18219;
        3: hb_coef = -25'sd143000;
        4: hb_coef = 25'sd670146;
        5: hb_coef = -25'sd2369501;
        6: hb_coef = 25'sd10213660;
        default: hb_coef = 25'sd0;
      endcase
      default: hb_coef = 25'sd0;
    endcase
  end
endfunction
