// Halfband x2 interpolator stage, time-multiplexed MAC (one multiplier).
//
// For every input sample x[k] (in_stb) it emits two output samples:
//   at in_stb + DLY            : y_even = sum_i g[i] * (d[i] + d[2M-1-i])  (MAC)
//   at in_stb + DLY + PERIOD/2 : y_odd  = d[M-1]                             (centre tap)
// g[i] = 2*h[2i] (Q.24) come from hb_coefs.vh, generated by
// model/fixed_golden.py, which is the bit-exact reference for this module.
//
// Samples: signed W bits, value = int / 2^24. Rounding: add half, >>> 24.
// The MAC needs M+1 clocks, so DLY > M+1 and DLY + PERIOD/2 < PERIOD.

`timescale 1ns / 1ps

module hb_stage #(
    parameter integer STAGE  = 1,     // selects the coefficient set
    parameter integer M      = 8,     // MAC taps = (NT + 1) / 4
    parameter integer PERIOD = 256,   // clocks between input samples
    parameter integer DLY    = 24,    // clocks from in_stb to the first output
    parameter integer W      = 28
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                in_stb,
    input  wire signed [W-1:0] in_x,
    output reg                 out_stb,
    output reg  signed [W-1:0] out_y
);

`include "hb_coefs.vh"

    localparam integer L = 2 * M;
    localparam integer AW = 64;

    reg signed [W-1:0] d [0:L-1];
    reg [9:0]          cnt;           // clocks since in_stb
    reg                run;
    reg [5:0]          mi;            // MAC index
    reg signed [AW-1:0] acc;

    // one MAC term: g[mi] * (d[mi] + d[L-1-mi])
    wire signed [W:0]    pre  = d[mi] + d[L - 1 - mi];
    wire signed [24:0]   g    = hb_coef(STAGE, mi);
    wire signed [AW-1:0] prod = pre * g;

    // rounding and saturation of the accumulator to W bits
    wire signed [AW-1:0] acc_r = (acc + (64'sd1 <<< 23)) >>> 24;
    wire signed [W-1:0]  acc_sat =
        (acc_r >  $signed({{(AW-W+1){1'b0}}, {(W-1){1'b1}}})) ? {1'b0, {(W-1){1'b1}}} :
        (acc_r < -$signed({{(AW-W+1){1'b0}}, {(W-1){1'b1}}}) - 1) ? {1'b1, {(W-1){1'b0}}} :
        acc_r[W-1:0];

    integer j;

    always @(posedge clk) begin
        if (rst) begin
            for (j = 0; j < L; j = j + 1) d[j] <= {W{1'b0}};
            cnt     <= 10'd0;
            run     <= 1'b0;
            mi      <= 6'd0;
            acc     <= {AW{1'b0}};
            out_stb <= 1'b0;
            out_y   <= {W{1'b0}};
        end else begin
            out_stb <= 1'b0;
            if (in_stb) begin
                d[0] <= in_x;
                for (j = 1; j < L; j = j + 1) d[j] <= d[j - 1];
                cnt <= 10'd0;
                run <= 1'b1;
                mi  <= 6'd0;
                acc <= {AW{1'b0}};
            end else if (run) begin
                cnt <= cnt + 10'd1;
                // clocks 1..M after in_stb: accumulate (delay line already shifted)
                if (mi < M) begin
                    acc <= acc + prod;
                    mi  <= mi + 6'd1;
                end
                if (cnt + 10'd1 == DLY) begin
                    out_y   <= acc_sat;
                    out_stb <= 1'b1;
                end
                if (cnt + 10'd1 == DLY + PERIOD / 2) begin
                    out_y   <= d[M - 1];
                    out_stb <= 1'b1;
                    run     <= 1'b0;
                end
            end
        end
    end

endmodule
