// generated by model/fixed_golden.py - do not edit
// noise shaper H = NTF - 1 (transposed DF-II), Q.28
function signed [33:0] ns_hb;
  input integer i;
  begin
    case (i)
      0: ns_hb = -34'sd572476261;
      1: ns_hb = 34'sd1723002664;
      2: ns_hb = -34'sd2053779946;
      3: ns_hb = 34'sd1128001805;
      4: ns_hb = -34'sd238720752;
      default: ns_hb = 34'sd0;
    endcase
  end
endfunction
function signed [33:0] ns_a;
  input integer i;
  begin
    case (i)
      0: ns_a = -34'sd767704997;
      1: ns_a = 34'sd955366694;
      2: ns_a = -34'sd624589412;
      3: ns_a = 34'sd212179452;
      4: ns_a = -34'sd29714704;
      default: ns_a = 34'sd0;
    endcase
  end
endfunction
